Repository CSharp-levelup/Dev-Do-List, pull requests merged in 2024-04, with the labels that each got.

#5 Feature/jesse/8 oauth2 and jwt
  dev-do-list-server/Controllers/TestController.cs
  dev-do-list-server/Controllers/WeatherForecastController.cs
  dev-do-list-server/Jwt/JwtOptions.cs
  dev-do-list-server/Jwt/TokenEndpoint.cs
  dev-do-list-server/Models/GithubUser.cs
  dev-do-list-server/Program.cs
  dev-do-list-server/Services/TestService.cs
  dev-do-list-server/WeatherForecast.cs
  dev-do-list-server/dev-do-list-server.csproj
Labels: enhancement

#14 Role endpoint and Securing endpoints
  dev-do-list-server/Controllers/AuthController.cs
  dev-do-list-server/Controllers/RoleController.cs
  dev-do-list-server/Controllers/TestController.cs
  dev-do-list-server/Controllers/UserController.cs
  dev-do-list-server/Models/RoleType.cs
  dev-do-list-server/Models/User.cs
  dev-do-list-server/Program.cs
  dev-do-list-server/Repositories/RoleRepository.cs
  dev-do-list-server/Repositories/UserRepository.cs
  dev-do-list-server/Services/AuthService.cs
  dev-do-list-server/Services/TestService.cs
  dev-do-list-server/dev-do-list-server.csproj
Labels: enhancement

#20 Get user by username in token implemented
  dev-do-list-server/Controllers/UserController.cs
  dev-do-list-server/Repositories/UserRepository.cs
Labels: enhancement

#36 Feature/michael/release
  .github/release-drafter.yml
  .github/workflows/cli-enforce-label.yml
  .github/workflows/cli-release.yml
Labels: major

#37 Testing release workflows
  .github/workflows/cli-release.yml
  dev-do-list-cli/Program.cs
Labels: major

#38 Feature/michael/testing release
  .github/workflows/cli-release.yml
Labels: major

#39 Testing release
  dev-do-list-cli/Program.cs
Labels: major

#41 Release test
  dev-do-list-cli/Program.cs
Labels: major

#46 Feature/michael/package exe
  .github/workflows/cli-release.yml
  dev-do-list-cli/dev-do-list-cli.csproj
Labels: minor

#48 Deleted old frontend (finally)
  dev-do-list-frontend/.eslintrc.cjs
  dev-do-list-frontend/.gitignore
  dev-do-list-frontend/Procfile
  dev-do-list-frontend/README.md
  dev-do-list-frontend/index.html
  dev-do-list-frontend/package-lock.json
  dev-do-list-frontend/package.json
  dev-do-list-frontend/public/vite.svg
  dev-do-list-frontend/src/App.css
  dev-do-list-frontend/src/App.jsx
  dev-do-list-frontend/src/assets/hidepass_export.svg
  dev-do-list-frontend/src/assets/logo.svg
  dev-do-list-frontend/src/assets/react.svg
  dev-do-list-frontend/src/assets/showpass_export.svg
  dev-do-list-frontend/src/components/dataCards.css
  dev-do-list-frontend/src/components/dataCards.jsx
  dev-do-list-frontend/src/components/usersData.json
  dev-do-list-frontend/src/index.css
  dev-do-list-frontend/src/main.jsx
  dev-do-list-frontend/src/pages/Dashboard.css
  dev-do-list-frontend/src/pages/Dashboard.jsx
  dev-do-list-frontend/src/pages/Login.css
  dev-do-list-frontend/src/pages/Login.jsx
  dev-do-list-frontend/vite.config.js
Labels: chore

#50 Enable reflection for serialization
  dev-do-list-cli/dev-do-list-cli.csproj
Labels: major

#51 Fix/michael/fix cli
  dev-do-list-cli/dev-do-list-cli.csproj
Labels: major
